ORG_COMMON_NAME='MOCA'
ORG_GITHUB_NAME='mocafinancial'
ORG_LEGAL_NAME='Moca Financial Inc'
ORG_ADDRESS='430 Old Firetower Rd
Bastrop, TX 78602'
ORG_NAICS='1'
ORG_NPM_REGISTRY='https://npm.pkg.github.com/'
ORG_NPM_SCOPE='moca'
ORG_NICK_NAME='moca'
ORG_POLICY_REPO='@moca/moca-financial-policy'
ORG_STAFF_REPO='@moca/moca-financial'
ORG_STRUCTURE='node_modules/@moca/moca-financial-policy/org_structure.json'
